name: Build & Push Docker (GHCR)
on:
  push:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/omnirevolve-dev:humble
            ghcr.io/${{ github.repository_owner }}/omnirevolve-dev:latest
